# Config which is intended for usage with pytest in docker
---
api:
  prefix: "/api"
  secrets:
    secret_key: "test_key"
storage:
  uploads:
    dir: "/opt/updateapi/uploads/"
db:
  mongo_uri: "localhost:27017"
meta:
  modname: "TestMod"
