name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mongodb:
          image: mongo
          ports:
            - 27017:27017
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }} 
    - name: install dependencies
      run: pip install -r requirements.txt
    - name: change directory
      run: cd src  
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint pytest
    - name: Analysing the code with pylint
      run: |
        pylint -E $(git ls-files '*.py')
    - name: Test with pytest
      run: |
        cd src
        export UPDATEAPI_CONFIG=../config/test.yaml
        pytest updateapi

